language: cpp

os:
  - linux

dist: trusty

sudo: required

compiler:
  - gcc

env:
  - BUILD_TYPE = Release

# Handle git submodules yourself
git:
  submodules: false

before_install:
  # cmake
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  # g++-5
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get -qq update
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  # cmake
  - sudo apt-get -qq install cmake
  # g++-5
  - if [ "$CXX" = "g++" ]; then sudo apt-get -qq install gcc-5 g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CC="gcc-5" CXX="g++-5"; fi
  # eigen3
  - sudo apt-get -qq install libeigen3-dev
  # glew
  #- sudo apt-get -qq install libglew-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-w ..

script:
  - $CXX --version
  - make -j

notifications:
  email: false
